// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cndoeiyrrfjnbetewilr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZG9laXlycmZqbmJldGV3aWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTc2NTgsImV4cCI6MjA2NzAzMzY1OH0.HWif1PE_FmCAFHYD2HwUApbv-vuTA09HowBUuDCONIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});